local M = {}

-- local mason_packages = vim.fn.expand("$MASON/packages")
-- local vue_ls_path = mason_packages .. "/vue-language-server/node_modules/@vue/language-server"
-- local svelte_ls_path = mason_packages .. "/svelte-language-server"
--
-- M.ts_ls = {
--   filetypes = { "typescript", "javascript", "vue" },
--   init_options = {
--     preferences = {
--       includeinlayparameternamehints = "all",
--       includeinlayparameternamehintswhenargumentmatchesname = true,
--       includeinlayfunctionparametertypehints = true,
--       includeinlayvariabletypehints = true,
--       includeinlaypropertydeclarationtypehints = true,
--       includeinlayfunctionlikereturntypehints = true,
--       includeinlayenummembervaluehints = true,
--       importmodulespecifierpreference = "non-relative",
--     },
--     plugins = {
--       {
--         name = "@vue/typescript-plugin",
--         location = vue_ls_path,
--         languages = { "vue" },
--       },
--       {
--         name = "typescript-svelte-plugin",
--         location = svelte_ls_path,
--         languages = { "javascript", "typescript", "svelte" },
--       },
--     },
--   },
-- }
--
return M
